name: "Bacon's Palace"
favicon: null
layout_spectrum: 0.6824595292564481
typography_spectrum: 0.5841818018816411
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6826523025520146
  lightness: 0.1843916466459632
  saturation: 0.4977793914731592
  rhythmicContrast: 0.8431392300408334
purpose: []
